notifications:
  email: false
dist: xenial
language: python
services:
  docker
python:
- 3.6
- 3.7
- 3.8
- pypy3
env:
  global:
  - DOCKER_BASE_IMAGE="multiarch/alpine"
  - DOCKER_IMAGE_APPENDIX="latest-stable"
  - LOCAL_IMAGE_NAME="local/xbox-smartglass-core"
  jobs:
  - ARCH="aarch64"
  - ARCH="amd64"
  - ARCH="i386"
  - ARCH="armhf"
  - ARCH="armv7"
  - ARCH="arm64"
before_install:
- export BUILD_FROM="$DOCKER_BASE_IMAGE:$ARCH-$DOCKER_IMAGE_APPENDIX"
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

install:
- pip install -U tox-travis
- pip install -e .[dev]

script:
- tox
- docker build -t $LOCAL_IMAGE_NAME:$TRAVIS_COMMIT-$ARCH --build-arg BUILD_FROM="$BUILD_FROM" .

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: "INUnilgdq+RF6aIHyZ8g3kuiaWKbp4xrIh92A+xCnszIbeUR7YJyji4HV8BTpyY/EPm2dzsL6Pn3zBTswr8vsfbvJHgNRhnpy0T2RH2SE4j4PGjku67GMTOrS3ksdzsG61TLXmWRz03PmkwhNt7pjFQswsuu3pvBcrIVTQB4BW6++4vXouPkK3Vu9aOKLJzMseTStLk1ZLmKOFYMZIRybkqWKDVF7TJ5PBpS7ND/kRo+3CRanLehnmJC3GZJ4xHnf3kpxL2U9sAv0e8RsY/FoSTYAq/b83sG4TDNwd0Ygd7+Qz8SIiWLvULKXAOitvgVAims3d0EunYbh7b+GNDt2ep6Ik/5ZLdqdzh8aZY4g2kf9D75m1aTEikCz8zHqrlWB0jHIgnrIA/y4yKhfOEUMmesVLlNo3MeRbX6fLOtlAIbKpKseThTzziPysF3aQeNJl0Tjmvv03nKgKMAos4wOu+4ncwoflw+Tc39vIVbxUCni3dkZFbN18CJy2Re7s5Tuk6alcXGwtL1Ib5KWcry2plXWIClZJJLI3G+tyfC/vZxt5qnJdphjBnDNVrAU0obERqnCzbhRpcQBG6B0ZOQrE+JaKx4aHvehl4saFOYLIOW9FTq4Lo2Xe6q9DHrIRMgBeR2Uezrll+eUa+naQ1CLoWIblPIHa3khQ+Rl7pnGd0="
  on:
    tags: true
    branch: master
    python: 3.6
